// src/lib/roofStyles.js

export const ROOF_STYLES = [
  {
    id: "metal-charcoal",
    label: "Charcoal Metal",
    category: "Metal",
    prompt: "charcoal grey metal standing seam roof panels with clean vertical lines",
    swatch: "#4B5563",
    popular: true,
  },
  {
    id: "metal-white",
    label: "White Metal",
    category: "Metal",
    prompt: "crisp white painted metal standing seam roof panels",
    swatch: "#F3F4F6",
  },
  {
    id: "metal-copper",
    label: "Aged Copper",
    category: "Metal",
    prompt: "aged green copper patina standing seam metal roof with natural weathering",
    swatch: "#4A7C6F",
  },
  {
    id: "metal-red",
    label: "Barn Red",
    category: "Metal",
    prompt: "deep barn red metal standing seam roof panels",
    swatch: "#991B1B",
  },
  {
    id: "green-metal",
    label: "Forest Green",
    category: "Metal",
    prompt: "deep forest green metal standing seam roof panels",
    swatch: "#14532D",
  },
  {
    id: "slate-dark",
    label: "Dark Slate",
    category: "Slate",
    prompt: "dark charcoal natural slate roof tiles with subtle texture variation",
    swatch: "#374151",
    popular: true,
  },
  {
    id: "slate-blue",
    label: "Blue-Grey Slate",
    category: "Slate",
    prompt: "blue-grey natural slate roof tiles in a traditional staggered pattern",
    swatch: "#4B6478",
  },
  {
    id: "clay-terracotta",
    label: "Terracotta Clay",
    category: "Clay Tile",
    prompt: "warm terracotta orange clay barrel roof tiles in a traditional Mediterranean style",
    swatch: "#C2714F",
    popular: true,
  },
  {
    id: "clay-red",
    label: "Spanish Red",
    category: "Clay Tile",
    prompt: "deep red Spanish clay mission roof tiles in a classic curved pattern",
    swatch: "#B91C1C",
  },
  {
    id: "cedar-natural",
    label: "Natural Cedar",
    category: "Wood",
    prompt: "natural weathered cedar wood shake shingles with organic texture",
    swatch: "#92613A",
  },
  {
    id: "cedar-grey",
    label: "Weathered Cedar",
    category: "Wood",
    prompt: "silver-grey weathered cedar shake shingles aged by the elements",
    swatch: "#9CA3AF",
  },
  {
    id: "asphalt-charcoal",
    label: "Charcoal Shingles",
    category: "Asphalt",
    prompt: "dimensional architectural asphalt shingles in charcoal black with subtle shadow lines",
    swatch: "#1F2937",
    popular: true,
  },
  {
    id: "asphalt-wood",
    label: "Weathered Wood",
    category: "Asphalt",
    prompt: "dimensional architectural asphalt shingles in weathered wood brown tones",
    swatch: "#78583A",
  },
  {
    id: "rubber-black",
    label: "Flat Black",
    category: "Flat",
    prompt: "smooth matte black rubber EPDM flat roof with clean edges",
    swatch: "#111827",
  },
  {
    id: "solar",
    label: "Solar Tiles",
    category: "Solar",
    prompt: "sleek black solar roof tiles seamlessly integrated flush with the roofline",
    swatch: "#0F172A",
    popular: true,
  },
  {
    id: "custom",
    label: "Custom…",
    category: "Custom",
    prompt: "",
    swatch: null,
    isCustom: true,
  },
];

export const CATEGORIES = ["All", ...new Set(ROOF_STYLES.map((r) => r.category))];
